import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  DynamicContextProvider,
  SolanaWalletConnectors,
  EthereumWalletConnectors,
  FlowWalletConnectors,
  CosmosWalletConnectors,
  BloctoEvmWalletConnectors,
  AlgorandWalletConnectors,
  StarknetWalletConnectors,
  MagicWalletConnectors,
  DynamicWagmiConnector,
} from "../lib/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "f0b977d0-b712-49f1-af89-2a24c47674da",
          walletConnectors: [
            EthereumWalletConnectors,
            FlowWalletConnectors,
            CosmosWalletConnectors,
            BloctoEvmWalletConnectors,
            AlgorandWalletConnectors,
            StarknetWalletConnectors,
            MagicWalletConnectors,
            SolanaWalletConnectors,
          ],
        }}
      >
        <DynamicWagmiConnector>
          <body className={inter.className}>{children}</body>
        </DynamicWagmiConnector>
      </DynamicContextProvider>
    </html>
  );
}
